name: Test JMeter Action

on:
  push:
    branches:
      - main
jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - name: JMeter Test
        uses: ./
        with:
          test-plan-path: ./jmeter/tests/soitec.jmx
          args: ""
          
      - name: Upload Results
        uses: ./
        with:
          name: jmeter-results
          path: result.jtl